git clone https://github.com/krb5/krb5.git
git clone https://android.googlesource.com/platform/external/libmpeg2
git clone https://android.googlesource.com/platform/external/libavc
git clone https://github.com/gpac/gpac.git
git clone https://github.com/nothings/stb.git
git clone https://github.com/Exiv2/exiv2.git
git clone git://w1.fi/hostap.git
git clone https://github.com/GNOME/libxml2.git
git clone https://github.com/bytecodealliance/wasm-micro-runtime.git
git clone https://github.com/p11-glue/p11-kit.git
git clone https://github.com/espeak-ng/espeak-ng.git
git clone https://github.com/lz4/lz4.git
git clone https://github.com/mity/md4c.git
git clone https://github.com/libimobiledevice/libplist.git
git clone https://github.com/bfabiszewski/libmobi.git
git clone https://github.com/libsndfile/libsndfile.git
git clone https://github.com/mruby/mruby.git
git clone https://github.com/SELinuxProject/selinux.git
git clone https://github.com/LibRaw/LibRaw.git
git clone https://github.com/uber/h3.git
git clone https://github.com/samtools/htslib.git
git clone https://github.com/kjdev/hoextdown.git
git clone https://github.com/sleuthkit/sleuthkit.git
git clone https://github.com/assimp/assimp.git
git clone https://github.com/facebook/zstd.git
git clone https://github.com/hunspell/hunspell.git
git clone https://github.com/AcademySoftwareFoundation/openexr.git
git clone https://github.com/stefanberger/libtpms.git
git clone https://github.com/irssi/irssi.git
git clone https://github.com/harfbuzz/harfbuzz.git
git clone https://github.com/Blosc/c-blosc.git
git clone https://github.com/json-c/json-c.git
git clone https://github.com/nlohmann/json.git
